"""Add owner id to group table

Revision ID: 92cae7ab3f0f
Revises: ee5d0feb1a8a
Create Date: 2023-11-20 22:00:47.842367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92cae7ab3f0f"
down_revision: Union[str, None] = "ee5d0feb1a8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("group", sa.Column("owner_id", sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group", "owner_id")
    # ### end Alembic commands ###
